<iframe src="https://bettysfitness.github.io/Blog/" 
        width="100%" 
        height="800px" 
        style="border:none;">
</iframe><a href="https://bettysfitness.github.io/Blog/" target="_blank">
  Visit My Blog
</a>name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
